### ISSUE TITLE
Does the latest PoShPACLI work with this?

### ISSUE THREAD

**Issue by mechamouse3d** [pspete/CyberArk-PowerTools#3]
I receive an error when trying to run Backup-Connection Component

> The term 'Initialize-PoShPACLI' is not recognized as the name of a cmdlet

**Comment by pspete** [comment]
Hey @chyuen94 - I'd forgotten all about this repo....
The scripts here have not been updated to work with the latest PoShPACLI.
You should be able download the old version from [here](https://github.com/pspete/PoShPACLI/tree/9d31d1d06d73d034b863a22dbbdad6b3a8158856)

**Comment by chyuen94** [comment]
@pspete One more question!
When using the Credential parameter in Backup-ConnectionComponent, is it possible to use a cred file? I am trying to connect through LDAP
